[package]
name = "dexter-vault"
version = "1.0.0"
authors = ["AstroTechLabs"]
edition = "2021"
description = "Persistence DEX Factory contract - entry point to create new pools. Maintains directory for all pools"
license = "MIT"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
dexter = { path = "../../packages/dexter", default-features = false }
cosmwasm-std = { version = "1.1" }
cw-storage-plus = "0.15"
cw2 = "0.15"
cw20 = { version = "0.15" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.20" }
protobuf = { version = "2", features = ["with-bytes"] }
serde-json-wasm = "0.4.1"
cosmwasm-schema = "1.1"

[dev-dependencies]
stable5pool = { path = "../pools/stable_5pool"}
weighted-pool = { path = "../pools/weighted_pool"}
lp-token = { path = "../lp_token"}
dexter-multi-staking = { path = "../multi_staking"}

cw-multi-test = "0.13.2"
cw20 = { version = "0.15" }
