[workspace]
members = [
    "contracts/keeper", 
    "contracts/vault", 
    "contracts/lp_token", 
    "contracts/stable_5pool", 
    "contracts/stable_pool", 
    "contracts/xyk_pool", 
    "contracts/weighted_pool", 
    "contracts/dexter_generator/*", 
    # "contracts/*",
    "packages/*"
]


[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true