[package]
name = "dexter"
version = "1.0.0"
authors = ["AstroTechLabs"]
edition = "2021"
description = "DEX on Persistence tendermint chain"
repository = "https://github.com/persistenceOne/dexter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "0.16.0"
cw20-base = { version = "0.16.0", features = ["library"] }
cosmwasm-std = "1.1.5"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
cw-storage-plus = { version = "0.13.2" }
uint = "0.9.1"
itertools = "0.10"
protobuf = { version = "2", features = ["with-bytes"] }
thiserror = { version = "1.0.20" }
cosmwasm-schema = "1.1.5"

[dev-dependencies]
cosmwasm-schema = "1.0.0"
