[package]
name = "dexter"
version = "1.0.0"
authors = ["AstroTechLabs"]
edition = "2021"
description = "DEX on Persistence tendermint chain"
repository = "https://github.com/persistenceOne/dexter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "1.1.0"
cw20-base = { version = "1.1.0", features = ["library"] }
cosmwasm-std = "1.2.7"
schemars = "0.8.12"
serde = { version = "1.0.171", default-features = false, features = ["derive"] }
cw-storage-plus = "1.1.0"
uint = "0.9.5"
itertools = "0.10.5"
protobuf = { version = "2", features = ["with-bytes"] }
thiserror = "1.0.43"
cosmwasm-schema = "1.2.7"

