[package]
name = "dexter"
version = "1.3.0"
authors = ["PersistenceLabs"]
edition = "2021"
description = "Dex optimized for liquid staked assets"
repository = "https://github.com/dexter-zone/dexter_core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = "1.0.1"
cw20-base = { version = "1.0.1", features = ["library"] }
cosmwasm-std = "1.5.3"
schemars = "0.8.11"
serde = { version = "1.0.152", default-features = false, features = ["derive"] }
cw-storage-plus = "1.0.1"
uint = "0.9.5"
itertools = "0.10.5"
protobuf = { version = "2", features = ["with-bytes"] }
thiserror = "1.0.38"
cosmwasm-schema = "1.2.1"

